[package]
name = "scope-monitor"
description = "A multi-platform serial monitor with user-extensible features"
authors = ["Matheus T. dos Santos <matheuswhite1@protonmail.com>"]
version = "0.1.1"
edition = "2021"
rust-version = "1.66.1"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/matheuswhite/scope-rs"
homepage = "https://github.com/matheuswhite/scope-rs"
keywords = ["serial", "monitor", "windows", "linux", "plugin"]
exclude = ["/imgs/", "/videos/", "/assets/", "/.git/", "/.github/", "/.venv/", "/.gitignore", "/cmd.yaml", "/CONTRIBUTING.md", '/.idea/']

[badges]
maintenance = { status = 'actively-developed' }

[[bin]]
name = "scope"
path = "src/main.rs"

[dependencies]
serialport = "4.3.0"
tui = "0.19.0"
crossterm = "0.25.0"
chrono = "0.4.23"
serde = "1.0"
serde_yaml = "0.9"
rand = "0.8.5"
clap = { version = "4.1.9", features = ["derive"] }
rlua = "0.19.8"
anyhow = "1.0.79"
homedir = "0.2.1"
