name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Check on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libudev-sys
      run: sudo apt-get install -y libudev-dev
    - name: Build
      run: cargo build --release --verbose
  build-windows:
    name: Check on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
  build-macos:
    name: Check on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
